"""add subscription-2

Revision ID: 1391ea6ade66
Revises: 9c35e2ac96b3
Create Date: 2024-06-08 08:18:27.254444

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1391ea6ade66'
down_revision = '9c35e2ac96b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('usage_limits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', models.StringUUID(), nullable=False))
        batch_op.add_column(sa.Column('subscription_id', models.StringUUID(), nullable=False))
        batch_op.add_column(sa.Column('is_yearly_monthly_plan', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('monthly_cycle', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_limits', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('monthly_cycle')
        batch_op.drop_column('is_yearly_monthly_plan')
        batch_op.drop_column('subscription_id')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###