"""add subscription

Revision ID: 608df500eed3
Revises: 1391ea6ade66
Create Date: 2024-06-08 09:39:55.898520

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608df500eed3'
down_revision = '1391ea6ade66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('docs_processing',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('docs_processing',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###