"""add data_api

Revision ID: 628b2521ce75
Revises: 608df500eed3
Create Date: 2024-06-08 12:53:11.495069

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628b2521ce75'
down_revision = '608df500eed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_api_applications',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.StringUUID(), nullable=False),
    sa.Column('data_api_id', models.StringUUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_api_applications_pkey')
    )
    op.create_table('data_api_calls',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.StringUUID(), nullable=False),
    sa.Column('data_api_id', models.StringUUID(), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=False),
    sa.Column('billing_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='data_api_calls_pkey')
    )
    op.create_table('data_apis',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('price_per_call', sa.Integer(), nullable=False),
    sa.Column('authorization_method', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='data_apis_pkey')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_apis')
    op.drop_table('data_api_calls')
    op.drop_table('data_api_applications')
    # ### end Alembic commands ###