"""empty message

Revision ID: 64882f1a798f
Revises: 16830a790f0f
Create Date: 2024-03-19 03:02:50.584871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64882f1a798f'
down_revision = '16830a790f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
                    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('tenant_id', postgresql.UUID(), nullable=False),
                    sa.Column('app_id', postgresql.UUID(), nullable=False),
                    sa.Column('app_key', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('interact_role', sa.String(length=255), nullable=False),
                    sa.Column('interact_goal', sa.String(length=512), nullable=False),
                    sa.Column('interact_tools', sa.JSON(), nullable=False),
                    sa.Column('interact_nums', sa.Integer(), nullable=False),
                    sa.Column('user_role', sa.String(length=255), nullable=False),
                    sa.Column('user_goal', sa.String(length=512), nullable=False),
                    sa.Column('user_tools', sa.JSON(), nullable=False),
                    sa.Column('dataset_ids', sa.String(length=512), nullable=False),
                    sa.Column('language', sa.String(length=255), nullable=True),
                    sa.Column('permission', sa.String(length=255), server_default=sa.text("'only_me'::character varying"), nullable=False),
                    sa.Column('created_by', postgresql.UUID(), nullable=False),
                    sa.Column('updated_by', postgresql.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
                    sa.PrimaryKeyConstraint('id', name='scenarios_pkey')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenarios')
    # ### end Alembic commands ###
