"""modify meeting

Revision ID: 7e1595a5b9d0
Revises: 28f99c5d7991
Create Date: 2024-03-28 13:15:51.943272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e1595a5b9d0'
down_revision = '28f99c5d7991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
